name: Reuseable Deploy
on: 
    workflow_call:
        inputs:
            artifact_name:
                description: 'Name of the artifact to deploy'
                required: false
                default: 'dist'
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: ${{ inputs.artifact_name }}
            - name: List files
              run: ls
            - name: Ouput information
              run: echo "Deploying and uploading..."